title: Action de Recherche Graphes de connaissances géohistoriques
author: AR Graphes des connaissances géohistoriques
url: https://hueynemud.github.io/ar-gh-website/ # root address of the site
description: > # description of the site (multiple lines allowed)
  Cette action de recherche du <a href="https://gdr-magis.imag.fr/">GDR CNRS MAGIS</a> s'intéresse à l'extraction, la structuration et l'exploitation d'informations sur des faits ou des observations enregistrés dans un passé plus ou moins lointain et de leurs relations spatio-temporelles, et stockés dans divers types de documents (cartes, textes, images, etc.). Notre objectif principal est de proposer un lieu d'échange pour l'ensemble des chercheurs qui travaillent sur la création et la publication de graphes géohistoriques pour étudier l'évolution du territoire sur le temps long, et qui viennent parfois de communautés scientifiques très diverses: histoire, géographie, géomatique, vision par ordinateur, ingénierie des connaissances, etc. Ceci passe notamment par l’organisation de webinaires, ateliers, groupes de travail, etc. permettant de dresser un état des lieux des travaux de construction de graphes géohistoriques et des sources, vocabulaires, approches, et outils mobilisés pour y parvenir.

permalink: /:slug

favicon: "./logo.png" # relative path to site's favicon

#twitter:
#    username: abhinav # update or delete this
#    card: summary_large_image

#theme: moonwalk # if you are using GitHub Pages, change it to remote_theme: abhinavs/moonwalk
remote_theme: abhinavs/moonwalk

theme_config:
  appearance: "light" # can be "light", "dark" or "auto"
  appearance_toggle: true # if appearance can be switched by user
  back_home_text: "home.." # customize text for homepage link in post layout
  date_format: "%d-%m-%Y" # customize how date is formatted
  show_description: true # show blog description
  show_navbar: true # show horizontal navbar
  show_footer: true # show footer links in home page,add in _data/home.yml
  show_copyright: true # show copyright notice in footer
  # following keys are using to create home layout
  show_projects: true # show projects as cards, add in _data/home.yml
  show_blog: true # show blog posts added in _posts
  show_old_projects: true # show old projects as cards, add in _data/home.yml
  show_misc_list: false # show generic vertical list for misc details, add _data/home.yml
  show_reading_time: true # show number of words and reading time in the blog posts
  # options for "home" page
  home:
    title_projects: Activités
    title_misc_list: Details
    title_blog: Actualités
    title_old_projects: Old Projects

soopr:
  publish_token: "" # sign up at https://www.soopr.co to get your publish token and personalize share and reaction options

highlighter: rouge

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
